# Generated by Django 4.0.3 on 2022-03-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovies', '0002_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViewMovies.theater')),
            ],
        ),
    ]
