# Generated by Django 4.0.3 on 2022-03-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewMovies', '0004_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='id',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(default='Mov', max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(default='mov', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='theater',
            name='theater_name',
            field=models.CharField(max_length=70),
        ),
    ]
